include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/generated/**"

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - prefer_single_quotes
