// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:window_decoration/linux')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>()
external void cw_gtk_window_remove_decorations(
  ffi.Pointer<ffi.Void> gtk_window,
  ffi.Pointer<ffi.Void> fl_view,
);

@ffi.Native<ffi.Void Function()>()
external void cw_init_event_hooks_if_needed();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int, ffi.Int)>()
external void cw_window_begin_move_drag(
  ffi.Pointer<ffi.Void> gtk_window,
  int x,
  int y,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Void>,
    ffi.UnsignedInt,
    ffi.Int,
    ffi.Int,
  )
>()
external void cw_window_begin_resize_drag(
  ffi.Pointer<ffi.Void> gtk_window,
  int edge,
  int x,
  int y,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Void>,
    ffi.Int,
    ffi.Int,
    ffi.Int,
    ffi.Int,
  )
>()
external void cw_window_set_shadow_width(
  ffi.Pointer<ffi.Void> gtk_window,
  int top,
  int left,
  int bottom,
  int right,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, cw_delegate_config_t)>()
external void cw_gtk_window_init_delegate(
  ffi.Pointer<ffi.Void> gtk_window,
  cw_delegate_config_t config,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int cw_window_get_state(
  ffi.Pointer<ffi.Void> gtk_window,
);

abstract class cw_window_edge_t {
  static const int CW_WINDOW_EDGE_NORTH_WEST = 0;
  static const int CW_WINDOW_EDGE_NORTH = 1;
  static const int CW_WINDOW_EDGE_NORTH_EAST = 2;
  static const int CW_WINDOW_EDGE_WEST = 3;
  static const int CW_WINDOW_EDGE_EAST = 4;
  static const int CW_WINDOW_EDGE_SOUTH_WEST = 5;
  static const int CW_WINDOW_EDGE_SOUTH = 6;
  static const int CW_WINDOW_EDGE_SOUTH_EAST = 7;
}

final class cw_delegate_config_t extends ffi.Struct {
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>
  on_window_will_close;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>
  on_window_state_changed;
}

const int CW_WINDOW_STATE_WITHDRAWN = 1 << 0;
const int CW_WINDOW_STATE_ICONIFIED = 1 << 1;
const int CW_WINDOW_STATE_MAXIMIZED = 1 << 2;
const int CW_WINDOW_STATE_STICKY = 1 << 3;
const int CW_WINDOW_STATE_FULLSCREEN = 1 << 4;
const int CW_WINDOW_STATE_ABOVE = 1 << 5;
const int CW_WINDOW_STATE_BELOW = 1 << 6;
const int CW_WINDOW_STATE_FOCUSED = 1 << 7;
const int CW_WINDOW_STATE_TILED = 1 << 8;
const int CW_WINDOW_STATE_TOP_TILED = 1 << 9;
const int CW_WINDOW_STATE_TOP_RESIZABLE = 1 << 10;
const int CW_WINDOW_STATE_RIGHT_TILED = 1 << 11;
const int CW_WINDOW_STATE_RIGHT_RESIZABLE = 1 << 12;
const int CW_WINDOW_STATE_BOTTOM_TILED = 1 << 13;
const int CW_WINDOW_STATE_BOTTOM_RESIZABLE = 1 << 14;
const int CW_WINDOW_STATE_LEFT_TILED = 1 << 15;
const int CW_WINDOW_STATE_LEFT_RESIZABLE = 1 << 16;
